// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: copyfrom.go

package db

import (
	"context"
)

// iteratorForCreateAlbumArtists implements pgx.CopyFromSource.
type iteratorForCreateAlbumArtists struct {
	rows                 []CreateAlbumArtistsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAlbumArtists) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAlbumArtists) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AlbumID,
		r.rows[0].ArtistID,
	}, nil
}

func (r iteratorForCreateAlbumArtists) Err() error {
	return nil
}

func (q *Queries) CreateAlbumArtists(ctx context.Context, arg []CreateAlbumArtistsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"album_artist"}, []string{"album_id", "artist_id"}, &iteratorForCreateAlbumArtists{rows: arg})
}

// iteratorForCreateAlbumGenres implements pgx.CopyFromSource.
type iteratorForCreateAlbumGenres struct {
	rows                 []CreateAlbumGenresParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAlbumGenres) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAlbumGenres) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AlbumID,
		r.rows[0].GenreName,
	}, nil
}

func (r iteratorForCreateAlbumGenres) Err() error {
	return nil
}

func (q *Queries) CreateAlbumGenres(ctx context.Context, arg []CreateAlbumGenresParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"album_genre"}, []string{"album_id", "genre_name"}, &iteratorForCreateAlbumGenres{rows: arg})
}

// iteratorForCreateSongArtists implements pgx.CopyFromSource.
type iteratorForCreateSongArtists struct {
	rows                 []CreateSongArtistsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSongArtists) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSongArtists) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SongID,
		r.rows[0].ArtistID,
	}, nil
}

func (r iteratorForCreateSongArtists) Err() error {
	return nil
}

func (q *Queries) CreateSongArtists(ctx context.Context, arg []CreateSongArtistsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"song_artist"}, []string{"song_id", "artist_id"}, &iteratorForCreateSongArtists{rows: arg})
}

// iteratorForCreateSongGenres implements pgx.CopyFromSource.
type iteratorForCreateSongGenres struct {
	rows                 []CreateSongGenresParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateSongGenres) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateSongGenres) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].SongID,
		r.rows[0].GenreName,
	}, nil
}

func (r iteratorForCreateSongGenres) Err() error {
	return nil
}

func (q *Queries) CreateSongGenres(ctx context.Context, arg []CreateSongGenresParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"song_genre"}, []string{"song_id", "genre_name"}, &iteratorForCreateSongGenres{rows: arg})
}
