// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: genres.sql

package db

import (
	"context"
)

const createGenre = `-- name: CreateGenre :exec
INSERT INTO genres (name) VALUES ($1) ON CONFLICT DO NOTHING
`

func (q *Queries) CreateGenre(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, createGenre, name)
	return err
}

const deleteAllGenres = `-- name: DeleteAllGenres :exec
DELETE FROM genres
`

func (q *Queries) DeleteAllGenres(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteAllGenres)
	return err
}

const deleteGenre = `-- name: DeleteGenre :exec
DELETE FROM genres WHERE name = $1
`

func (q *Queries) DeleteGenre(ctx context.Context, name string) error {
	_, err := q.db.Exec(ctx, deleteGenre, name)
	return err
}

const findAllGenres = `-- name: FindAllGenres :many
SELECT name FROM genres
`

func (q *Queries) FindAllGenres(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, findAllGenres)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findGenre = `-- name: FindGenre :one
SELECT name FROM genres WHERE name = $1
`

func (q *Queries) FindGenre(ctx context.Context, name string) (string, error) {
	row := q.db.QueryRow(ctx, findGenre, name)
	err := row.Scan(&name)
	return name, err
}
