// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Album struct {
	ID             string
	Name           string
	Created        pgtype.Timestamptz
	Updated        pgtype.Timestamptz
	Year           *int32
	RecordLabels   *string
	MusicBrainzID  *string
	ReleaseTypes   *string
	IsCompilation  *bool
	ReplayGain     *float32
	ReplayGainPeak *float32
	ReleaseMbid    *string
}

type AlbumArtist struct {
	AlbumID  string
	ArtistID string
}

type AlbumGenre struct {
	AlbumID   string
	GenreName string
}

type AlbumRating struct {
	AlbumID  string
	UserName string
	Rating   int32
}

type AlbumStar struct {
	AlbumID  string
	UserName string
	Created  pgtype.Timestamptz
}

type Artist struct {
	ID            string
	Name          string
	Created       pgtype.Timestamptz
	Updated       pgtype.Timestamptz
	MusicBrainzID *string
}

type ArtistRating struct {
	ArtistID string
	UserName string
	Rating   int32
}

type ArtistStar struct {
	ArtistID string
	UserName string
	Created  pgtype.Timestamptz
}

type Genre struct {
	Name string
}

type Scrobble struct {
	UserName                string
	SongID                  string
	AlbumID                 *string
	Time                    pgtype.Timestamptz
	SongDurationMs          int32
	DurationMs              *int32
	SubmittedToListenbrainz bool
	NowPlaying              bool
}

type Song struct {
	ID             string
	Path           string
	AlbumID        *string
	Title          string
	Track          *int32
	Year           *int32
	Size           int64
	ContentType    string
	DurationMs     int32
	BitRate        int32
	SamplingRate   int32
	ChannelCount   int32
	DiscNumber     *int32
	Created        pgtype.Timestamptz
	Updated        pgtype.Timestamptz
	Bpm            *int32
	MusicBrainzID  *string
	ReplayGain     *float32
	ReplayGainPeak *float32
	Lyrics         *string
	CoverID        *string
}

type SongArtist struct {
	SongID   string
	ArtistID string
}

type SongGenre struct {
	SongID    string
	GenreName string
}

type SongRating struct {
	SongID   string
	UserName string
	Rating   int32
}

type SongStar struct {
	SongID   string
	UserName string
	Created  pgtype.Timestamptz
}

type System struct {
	Key   string
	Value string
}

type User struct {
	Name                       string
	EncryptedPassword          []byte
	EncryptedListenbrainzToken []byte
	ListenbrainzUsername       *string
}
