// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateAlbum(ctx context.Context, arg CreateAlbumParams) (*Album, error)
	CreateAlbumArtists(ctx context.Context, arg []CreateAlbumArtistsParams) (int64, error)
	CreateAlbumGenres(ctx context.Context, arg []CreateAlbumGenresParams) (int64, error)
	CreateArtist(ctx context.Context, arg CreateArtistParams) (*Artist, error)
	CreateGenre(ctx context.Context, name string) error
	CreateScrobbles(ctx context.Context, arg []CreateScrobblesParams) (int64, error)
	CreateSong(ctx context.Context, arg CreateSongParams) (*Song, error)
	CreateSongArtists(ctx context.Context, arg []CreateSongArtistsParams) (int64, error)
	CreateSongGenres(ctx context.Context, arg []CreateSongGenresParams) (int64, error)
	CreateUser(ctx context.Context, arg CreateUserParams) error
	DeleteAlbumArtists(ctx context.Context, albumID string) error
	DeleteAlbumGenres(ctx context.Context, albumID string) error
	DeleteAlbumsLastUpdatedBefore(ctx context.Context, updated pgtype.Timestamptz) error
	DeleteAllGenres(ctx context.Context) error
	DeleteArtistsLastUpdatedBefore(ctx context.Context, updated pgtype.Timestamptz) error
	DeleteGenre(ctx context.Context, name string) error
	DeleteNowPlaying(ctx context.Context, userName string) error
	DeleteSongArtists(ctx context.Context, songID string) error
	DeleteSongGenres(ctx context.Context, songID string) error
	DeleteSongsLastUpdatedBefore(ctx context.Context, updated pgtype.Timestamptz) error
	DeleteUser(ctx context.Context, name string) (string, error)
	FindAlbum(ctx context.Context, arg FindAlbumParams) (*FindAlbumRow, error)
	FindAlbumArtistRefsBySongs(ctx context.Context, songIds []string) ([]*FindAlbumArtistRefsBySongsRow, error)
	FindAlbumArtists(ctx context.Context, userName string) ([]*FindAlbumArtistsRow, error)
	FindAlbumsAlphabeticalByName(ctx context.Context, arg FindAlbumsAlphabeticalByNameParams) ([]*FindAlbumsAlphabeticalByNameRow, error)
	FindAlbumsByArtist(ctx context.Context, arg FindAlbumsByArtistParams) ([]*FindAlbumsByArtistRow, error)
	FindAlbumsByGenre(ctx context.Context, arg FindAlbumsByGenreParams) ([]*FindAlbumsByGenreRow, error)
	FindAlbumsByNameWithArtistMatchCount(ctx context.Context, arg FindAlbumsByNameWithArtistMatchCountParams) ([]*FindAlbumsByNameWithArtistMatchCountRow, error)
	FindAlbumsByYear(ctx context.Context, arg FindAlbumsByYearParams) ([]*FindAlbumsByYearRow, error)
	FindAlbumsHighestRated(ctx context.Context, arg FindAlbumsHighestRatedParams) ([]*FindAlbumsHighestRatedRow, error)
	FindAlbumsNewest(ctx context.Context, arg FindAlbumsNewestParams) ([]*FindAlbumsNewestRow, error)
	FindAlbumsRandom(ctx context.Context, arg FindAlbumsRandomParams) ([]*FindAlbumsRandomRow, error)
	FindAlbumsStarred(ctx context.Context, arg FindAlbumsStarredParams) ([]*FindAlbumsStarredRow, error)
	FindAllGenres(ctx context.Context) ([]string, error)
	FindArtist(ctx context.Context, arg FindArtistParams) (*FindArtistRow, error)
	FindArtistRefsByAlbums(ctx context.Context, albumIds []string) ([]*FindArtistRefsByAlbumsRow, error)
	FindArtistRefsBySongs(ctx context.Context, songIds []string) ([]*FindArtistRefsBySongsRow, error)
	FindArtistSimple(ctx context.Context, id string) (*Artist, error)
	FindArtistsByName(ctx context.Context, artistNames []string) ([]*Artist, error)
	FindGenre(ctx context.Context, name string) (string, error)
	FindGenresByAlbums(ctx context.Context, albumIds []string) ([]*FindGenresByAlbumsRow, error)
	FindGenresBySongs(ctx context.Context, songIds []string) ([]*FindGenresBySongsRow, error)
	FindGenresWithCount(ctx context.Context) ([]*FindGenresWithCountRow, error)
	FindPossibleScrobbleConflicts(ctx context.Context, arg FindPossibleScrobbleConflictsParams) ([]*Scrobble, error)
	FindRandomSongs(ctx context.Context, arg FindRandomSongsParams) ([]*FindRandomSongsRow, error)
	FindSong(ctx context.Context, id string) (*FindSongRow, error)
	FindSongByPath(ctx context.Context, path string) (*FindSongByPathRow, error)
	FindSongCount(ctx context.Context) (int64, error)
	FindSongWithoutAlbum(ctx context.Context, id string) (*Song, error)
	FindSongs(ctx context.Context, songIds []string) ([]*FindSongsRow, error)
	FindSongsByAlbum(ctx context.Context, arg FindSongsByAlbumParams) ([]*FindSongsByAlbumRow, error)
	FindSongsByMusicBrainzID(ctx context.Context, musicBrainzID *string) ([]*FindSongsByMusicBrainzIDRow, error)
	FindUnsubmittedLBScrobbles(ctx context.Context) ([]*FindUnsubmittedLBScrobblesRow, error)
	FindUser(ctx context.Context, name string) (*User, error)
	FindUsers(ctx context.Context) ([]*User, error)
	GetNowPlaying(ctx context.Context, userName string) (*Scrobble, error)
	GetNowPlayingSongs(ctx context.Context, userName string) ([]*GetNowPlayingSongsRow, error)
	GetStreamInfo(ctx context.Context, id string) (*GetStreamInfoRow, error)
	GetSystemValue(ctx context.Context, key string) (*System, error)
	InsertSystemValueIfNotExists(ctx context.Context, arg InsertSystemValueIfNotExistsParams) (*System, error)
	RemoveAlbumRating(ctx context.Context, arg RemoveAlbumRatingParams) error
	RemoveArtistRating(ctx context.Context, arg RemoveArtistRatingParams) error
	RemoveSongRating(ctx context.Context, arg RemoveSongRatingParams) error
	ReplaceSystemValue(ctx context.Context, arg ReplaceSystemValueParams) (*System, error)
	SearchAlbumArtists(ctx context.Context, arg SearchAlbumArtistsParams) ([]*SearchAlbumArtistsRow, error)
	SearchAlbums(ctx context.Context, arg SearchAlbumsParams) ([]*SearchAlbumsRow, error)
	SearchSongs(ctx context.Context, arg SearchSongsParams) ([]*SearchSongsRow, error)
	SetAlbumRating(ctx context.Context, arg SetAlbumRatingParams) error
	SetArtistRating(ctx context.Context, arg SetArtistRatingParams) error
	SetLBSubmittedByUsers(ctx context.Context, userNames []string) error
	SetSongRating(ctx context.Context, arg SetSongRatingParams) error
	StarAlbum(ctx context.Context, arg StarAlbumParams) error
	StarArtist(ctx context.Context, arg StarArtistParams) error
	StarSong(ctx context.Context, arg StarSongParams) error
	UnstarAlbum(ctx context.Context, arg UnstarAlbumParams) error
	UnstarArtist(ctx context.Context, arg UnstarArtistParams) error
	UnstarSong(ctx context.Context, arg UnstarSongParams) error
	UpdateAlbum(ctx context.Context, arg UpdateAlbumParams) error
	UpdateArtist(ctx context.Context, arg UpdateArtistParams) error
	UpdateSong(ctx context.Context, arg UpdateSongParams) error
	UpdateUserListenBrainzConnection(ctx context.Context, arg UpdateUserListenBrainzConnectionParams) (*User, error)
}

var _ Querier = (*Queries)(nil)
