// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: system.sql

package db

import (
	"context"
)

const insertSystemValueIfNotExists = `-- name: InsertSystemValueIfNotExists :one
INSERT INTO system (key, value) VALUES ($1, $2) ON CONFLICT (key) DO UPDATE SET key = $1 RETURNING key, value
`

type InsertSystemValueIfNotExistsParams struct {
	Key   string
	Value string
}

func (q *Queries) InsertSystemValueIfNotExists(ctx context.Context, arg InsertSystemValueIfNotExistsParams) (*System, error) {
	row := q.db.QueryRow(ctx, insertSystemValueIfNotExists, arg.Key, arg.Value)
	var i System
	err := row.Scan(&i.Key, &i.Value)
	return &i, err
}
